name: SBT Test

on: [push] 

jobs:
  build:
    name: Run SBT Tests
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 8  

    - name: Cache SBT dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
        restore-keys: ${{ runner.os }}-sbt-

    - name: Cache Ivy2 cache
      uses: actions/cache@v2
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-${{ hashFiles('**/*.sbt') }}
        restore-keys: ${{ runner.os }}-ivy-

    - name: Set up environment
      env:
        MYMAVENREPO_URL: ${{ secrets.MYMAVENREPO_URL }}
        MYMAVENREPO_USERNAME: ${{ secrets.MYMAVENREPO_USERNAME }}
        MYMAVENREPO_PASSWORD: ${{ secrets.MYMAVENREPO_PASSWORD }}
      run: |
        cd chess-analyzer
        echo "-Dmymavenrepo.url=${MYMAVENREPO_URL}" >> .sbtopts
        echo "-Dmymavenrepo.username=${MYMAVENREPO_USERNAME}" >> .sbtopts
        echo "-Dmymavenrepo.password=${MYMAVENREPO_PASSWORD}" >> .sbtopts
        echo "-Dsbt.global.base=sbt-cache/global" >> .sbtopts
        echo "-Dsbt.boot.directory=sbt-cache/boot" >> .sbtopts
        echo "-Dsbt.coursier.home=sbt-cache/coursier" >> .sbtopts
        cat .sbtopts

    - name: Run SBT tests
      working-directory: chess-analyzer
      run: sbt test